# Housing Dataset Preprocessing 
# Objective 
    The objective of this notebook is to perform EDA and do preprocessing

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("../Datasets/Housing.csv")
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [7]:
df.shape

(545, 13)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB

In [12]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [14]:
df.isnull().sum().sum()

np.int64(0)

Observation : There are no missing values in the dataset

In [22]:
df.dtypes

price               int64
area                int64
bedrooms            int64
bathrooms           int64
stories             int64
mainroad              str
guestroom             str
basement              str
hotwaterheating       str
airconditioning       str
parking             int64
prefarea              str
furnishingstatus      str
dtype: object

In [24]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [29]:
df.select_dtypes(include = [np.number]).shape[1]

6

In [47]:
X = df.drop('price' , axis = 1)
y = df['price']

In [48]:
X.dtypes

area                int64
bedrooms            int64
bathrooms           int64
stories             int64
mainroad              str
guestroom             str
basement              str
hotwaterheating       str
airconditioning       str
parking             int64
prefarea              str
furnishingstatus      str
dtype: object

In [50]:
X.select_dtypes(include = ["object"]).columns

C:\Users\SAHADHEEP\AppData\Local\Temp\ipykernel_4036\2048802586.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X.select_dtypes(include = ["object"]).columns

Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [53]:
for col in X.select_dtypes(include = ["object"]).columns:
    print(col)
    print(X[col].value_counts())
    print("-"*30)

mainroad
mainroad
yes    468
no      77
Name: count, dtype: int64
------------------------------
guestroom
guestroom
no     448
yes     97
Name: count, dtype: int64
------------------------------
basement
basement
no     354
yes    191
Name: count, dtype: int64
------------------------------
hotwaterheating
hotwaterheating
no     520
yes     25
Name: count, dtype: int64
------------------------------
airconditioning
airconditioning
no     373
yes    172
Name: count, dtype: int64
------------------------------
prefarea
prefarea
no     417
yes    128
Name: count, dtype: int64
------------------------------
furnishingstatus
furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64
------------------------------

C:\Users\SAHADHEEP\AppData\Local\Temp\ipykernel_4036\1941079198.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in X.select_dtypes(include = ["object"]).columns:

In [55]:
X = pd.get_dummies(X, columns = X.select_dtypes(include = ["object"]).columns, drop_first = True)

In [57]:
X.head()

,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,7420,4,2,3,2,True,False,False,False,True,True,False,False
1,8960,4,4,4,3,True,False,False,False,True,False,False,False
2,9960,3,2,2,2,True,False,True,False,False,True,True,False
3,7500,4,2,2,3,True,False,True,False,True,True,False,False
4,7420,4,1,2,2,True,True,True,False,True,False,False,False

In [60]:
X.shape

(545, 13)

In [62]:
X.select_dtypes(include = ["int64", "float64"]).columns

Index(['area', 'bedrooms', 'bathrooms', 'stories', 'parking'], dtype='str')

In [65]:
X.describe()

               area    bedrooms   bathrooms     stories     parking
count    545.000000  545.000000  545.000000  545.000000  545.000000
mean    5150.541284    2.965138    1.286239    1.805505    0.693578
std     2170.141023    0.738064    0.502470    0.867492    0.861586
min     1650.000000    1.000000    1.000000    1.000000    0.000000
25%     3600.000000    2.000000    1.000000    1.000000    0.000000
50%     4600.000000    3.000000    1.000000    2.000000    0.000000
75%     6360.000000    3.000000    2.000000    2.000000    1.000000
max    16200.000000    6.000000    4.000000    4.000000    3.000000

In [68]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [70]:
print(X_train.shape)
print(X_test.shape)

(436, 13)
(109, 13)

In [80]:


num_col = X_train.select_dtypes(include = ["int64", "float64"]).columns
num_col

Index(['area', 'bedrooms', 'bathrooms', 'stories', 'parking'], dtype='str')

In [82]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train[num_col] = scaler.fit_transform(X_train[num_col])
X_test[num_col] = scaler.transform(X_test[num_col])

In [84]:
X_train[num_col].describe()

               area      bedrooms     bathrooms       stories       parking
count  4.360000e+02  4.360000e+02  4.360000e+02  4.360000e+02  4.360000e+02
mean  -2.444528e-17 -3.666792e-17  8.148426e-18  8.148426e-18  8.148426e-18
std    1.001149e+00  1.001149e+00  1.001149e+00  1.001149e+00  1.001149e+00
min   -1.591502e+00 -2.622298e+00 -5.579503e-01 -9.124989e-01 -8.030587e-01
25%   -7.058568e-01 -1.283514e+00 -5.579503e-01 -9.124989e-01 -8.030587e-01
50%   -2.970974e-01  5.527092e-02 -5.579503e-01  2.542152e-01 -8.030587e-01
75%    5.476719e-01  5.527092e-02  1.539173e+00  2.542152e-01  3.679566e-01
max    5.016775e+00  4.071624e+00  5.733420e+00  2.587644e+00  2.709987e+00

In [ ]:
def preprocess_data(X , y , test_size = 0.2 , random_state = 42):
    X = pd.get_dummies(X, columns = X.select_dtypes(include = ["object"]).columns, drop_first = True)
    X_train , X_test , y_train , y_test = train_test_split(X, y, test_size = test_size, random_state = random_state)
    num_col = X_train.select_dtypes(include = ["int64", "float64"]).columns
    scaler = StandardScaler()
    X_train[num_col] = scaler.fit_transform(X_train[num_col])
    X_test[num_col] = scaler.transform(X_test[num_col])
    return X_train , X_test , y_train , y_test